# Generated by Django 5.2.7 on 2025-10-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFood', '0002_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
