# Generated by Django 5.2.7 on 2025-10-07 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFood', '0003_remove_recipe_image_url_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_hash', models.CharField(max_length=255, unique=True)),
                ('ai_response', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
