# Generated by Django 5.2.5 on 2025-08-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='maker',
            new_name='user',
        ),
    ]
