# Generated by Django 5.2.5 on 2025-08-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_maker_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='maker',
            new_name='user',
        ),
    ]
