services:
  web:
    build: .
    container_name: whattocook_web
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=WhatToCook.settings
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: whattocook_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: whattocook_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: whattocook_celery
    command: celery -A WhatToCook worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db_data:
